config/routes.rb
Rails.application.routes.draw do
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  get 'signup', to: 'doctors#new'
  resources :doctors, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    before_save {self.email=email.downcase}
    has_many :patients
    validates :firstName, presence: true, length: {minimum: 3, maximum: 25}
    validates :lastName, presence: true, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,uniqueness: {case_sensitive: false }, length: {maximum: 125},format: {with: VALID_EMAIL_REGEX}
    has_secure_password

end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :doctor
    validates :firstName,presence: true
    validates :lastName,presence: true
    validates :description, length:{ minimum:5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method:current_doctor,:logged_in?
    
    
    def current_doctor
      @current_doctor ||= Doctor.find(session[:doctor_id])  if session[:doctor_id]
    end
    def logged_in?
        !!current_doctor
    end
    
    def require_doctor
        if !logged_in?
            flash[:alert]="you need login to do this"
            redirect_to login_path
        end
    end
    

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    before_action :require_doctor, only:[:edit,:update]
    before_action :require_same_doctor, only:[:edit, :update,:destroy]
    
    

    def show
         @doctor=Doctor.find(params[:id])
         @patients = @doctor.patients.paginate(page: params[:page], per_page: 5)
    end
     def new
          @doctor=Doctor.new
     end
     def index
          @doctors=Doctor.paginate(page: params[:page], per_page: 5)
          
     end
     
     def edit
          @doctor=Doctor.find(params[:id])
     end
     def update
          @doctor=Doctor.find(params[:id])
          if @doctor.update(doctor_params)
             flash[:notice] = "Successfully Updated!"        
             redirect_to @doctor
          else
               render 'edit'
          end

     end 
     
     def create
          @doctor = Doctor.new(doctor_params)

           if @doctor.save
             session[:doctor_id]=@doctor.id
             flash[:notice] = "Successfully signup!"
             redirect_to @doctor
           else
              render 'new' 
           end
     end 


     
     
     private
     
     def doctor_params
          params.require(:doctor).permit(:firstName,:lastName,:email,:password)
     end
     
     def require_same_doctor
        if current_doctor!=@doctor
          flash[:alert] ="You are not allow to do this"
          redirect_to @doctor
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :require_doctor, except: [:show, :index]
  before_action :require_same_doctor, only: [:edit, :update,:destroy]
  

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.paginate(page: params[:page], per_page: 5)
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.doctor=current_doctor
      if @patient.save
        flash[:notice] = "New patient was created."
        redirect_to @patient
      else
         render :new 
      end
    end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
      if @patient.update(patient_params)
        flash[:notice] = "Changed successfully." 
        redirect_to @patient
      else
        render 'edit'
      end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end
   
   def patient_params
      params.require(:patient).permit(:firstName, :lastName, :description)
  end 
  
  def require_same_doctor
        if current_doctor!=@patient.doctor
          flash[:alert] ="You are not allow to do this"
          redirect_to @patient
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController< ApplicationController
    
    def new
        
    end    
    def create
        doctor= Doctor.find_by(email: params[:session][:email].downcase)
        if doctor && doctor.authenticate(params[:session][:password])
            session[:doctor_id]=doctor.id
            flash[:notice] = "welcome logged in"
            redirect_to doctor
        else
            flash.now[:alert] = "Something wrong"
            render 'new'
        end 
    end    
    def destroy
        session[:doctor_id]=nil
        flash[:notice] = "logged out"
        redirect_to root_path
    
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
    


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_form.html.erb
<div class="container">
    <% if @doctor.errors.any? %>
        <h2>The following errors:</h2>
        <ul>
            <% @doctor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <%= form_with(model: @doctor,local:true) do |f|%>
        <div class="form-group row">
            <%= f.label :firstName, class:"col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_field :firstName, class:"form-control" %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :lastName, class:"col-2 col-form-label"%>
            <div class="col-10">
                <%= f.text_field :lastName, class:"form-control"%>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :email  , class:"col-2 col-form-label"%>
            <div class="col-10">
                <%= f.email_field :email, class:"form-control"%>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :password, class:"col-2 col-form-label"%>
            <div class="col-10">
                <%= f.password_field :password, class:"form-control"%>
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <%= f.submit(@doctor.new_record? ? "Sign Up" :"Update", class:"btn btn-success") %>
        </div>
        <% end %>
        <%= link_to 'Back to the list page', patients_path %>

</div>

app/views/doctors/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Edit your profile</h1>


    <%= render 'form' %>
</div>

app/views/doctors/index.html.erb
<div class="apple_pagination">
    <%= will_paginate @doctors, :container => false %>
  </div>
<div id="page-content">
    <h1 class="text-center mt-4">Doctors</h1>
    <div class="container">
  <% @doctors.each do |doctor| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title"><%=link_to doctor.firstName+' '+doctor.lastName, doctor %></h5>
          <p class="card-text"><%= pluralize(doctor.patients.count, "patient") %></p>
            <%=link_to "View", doctor,class: "btn btn-success" %>
          <% if logged_in? && doctor==current_doctor %>
        
          <%=link_to "Edit", edit_doctor_path(doctor),class: "btn btn-info" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small></small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>
<div class="apple_pagination mb-4 mt-4">
    <%= will_paginate @doctors, :container => false %>
  </div>

app/views/doctors/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Sign up as a Docter</h1>
    <%= render 'form' %>
</div>

app/views/doctors/show.html.erb
<div id="page-content">
    <h1 class="text-center mt-4"><%= @doctor.firstName + ' ' + @doctor.lastName%>'s profile</h1>
    <div class="text-center mt-4">    
        <% if logged_in? && @doctor==current_doctor %>
        <%=link_to "Edit your profile", edit_doctor_path(@doctor),class: "btn btn-info" %>
        <% end %>
    </div>
<div class="apple_pagination">
    <%= will_paginate @patients, :container => false %>
  </div>
    <h3 class="text-center mt-4">Patients</h3>
    <%= render 'patients/patient' %>
</div>
<div class="apple_pagination mb-4 mt-4">
    <%= will_paginate @patients, :container => false %>
</div>

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>

app/views/layouts/_message.html.erb
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>

app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Han's Healthcare</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path,class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Doctors", doctors_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Patients
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Show all patients", patients_path, class:"dropdown-item" %>
              <% if logged_in? %>
                <%= link_to "Create new patient", new_patient_path, class:"dropdown-item" %>
              <% end %>

          </li>
          

          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class:"nav-link", method: :delete%>
            </li>
            <li class="nav-item">
                  <%= link_to current_doctor.firstName+"'s patients", doctor_path(current_doctor), class:"nav-link"%>
                </li>
            <% else %>
                <li class="nav-item">
                  <%= link_to "Login", login_path, class:"nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to "Signup", signup_path, class:"nav-link"%>
                </li>
            <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Healthcare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/nav' %>
    <%= render 'layouts/message'%>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
Hello This is about page!

app/views/pages/home.html.erb
<div id="page-content">
    <div class="container" id="home-container">
        <div class="jumbotron text-center">
          <h1 class="display-4">Welcome to Han's Healthcare</h1>
          <p class="lead">This is web to show the patient and doctor</p>
          <hr class="my-4">
          <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
          <% if !logged_in?%>
            <%= link_to "Doctor Sign", signup_path,class: "btn btn-success btn-lg" %>
          <% end %>
            <a class="btn btn-success btn-lg" href="#" role="button">Patient Sign</a>
        </div>
    </div>
</div>

app/views/patients/_form.html.erb
<div class="container">
    <% if @patient.errors.any? %>
        <h2>The following errors:</h2>
        <ul>
            <% @patient.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <%= form_with(model:@patient,local:true) do |f|%>
        <div class="form-group row">
            <%= f.label :firstName, class:"col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_field :firstName, class:"form-control" %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :lastName, class:"col-2 col-form-label"%>
            <div class="col-10">
                <%= f.text_field :lastName, class:"form-control"%>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :description, class:"col-2 col-form-label" %>
            <div class="col-10">
                <%= f.text_area :description, class:"form-control"%>
            </div>
        </div>
        <div class="form-group row justify-content-center">
            <%= f.submit %>
        </div>
        <% end %>
        <%= link_to 'Back to the list page', patients_path %>

</div>

app/views/patients/_patient.html.erb
<div class="container">
  <% @patients.each do |patient| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center">
        <div class="card-header">
          by <%= patient.doctor.firstName + ' ' + patient.doctor.lastName%>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%=link_to patient.firstName+' '+patient.lastName, patient_path(patient)%></h5>
          <p class="card-text"><%=truncate(patient.description,length: 100) %></p>
          <%=link_to "View", patient_path(patient),class: "btn btn-success" %>
          <% if logged_in? && patient.doctor==current_doctor %>
            <%=link_to "Edit", edit_patient_path(patient),class: "btn btn-info" %>
            <%=link_to "Delete", patient_path(patient),class: "btn btn-danger", method: :delete, data: {confirm:"Are U sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small></small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/patients/edit.html.erb
<h1 class="text-center mt-4">Edit Patient</h1>


<%= render 'form' %>

app/views/patients/index.html.erb
<h1 class="text-center mt-4">Patients</h1>
<div class="apple_pagination">
    <%= will_paginate @patients, :container => false %>
  </div>
<%= render 'patient' %>
<div class="apple_pagination mb-4 mt-4">
    <%= will_paginate @patients, :container => false %>
  </div> 

app/views/patients/new.html.erb
<h1 class="text-center mt-4">Create new Patient</h1>


<%= render 'form' %>

app/views/patients/show.html.erb
<h2 class="text-center mt-4"><%= @patient.firstName+' '+@patient.lastName %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center">
        <div class="card-header">
          by <%= @patient.doctor.firstName + ' ' + @patient.doctor.lastName%>
        </div>
        <div class="card-body">
          <p class="card-text"><%=simple_format(@patient.description) %></p>
          <% if logged_in? && @patient.doctor==current_doctor %>

          <%=link_to "Edit", edit_patient_path(@patient),class: "btn btn-info" %>
          <%=link_to "Delete", patient_path(@patient),class: "btn btn-danger", method: :delete, data: {confirm:"Are U sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small></small>
        </div>
      </div>
    </div>
  </div>
</div>